### ISSUE TITLE
missing_scope error

### ISSUE THREAD

**Issue by lastb0isct** [ont/slacker#12]
Getting this error when attempting to run the default config with a general rule to catch all of them to go to one channel -- seems it's getting stuck on an empty icon_url? Should I just remove the options I'm not going to use from the .yml?:

```ERROR:mail.log:SMTP session exception
Traceback (most recent call last):
  File "/usr/src/app/src/aiosmtpd/aiosmtpd/smtp.py", line 315, in _handle_client
    await method(arg)
  File "/usr/src/app/src/aiosmtpd/aiosmtpd/smtp.py", line 688, in smtp_DATA
    status = await self._call_handler_hook('DATA')
  File "/usr/src/app/src/aiosmtpd/aiosmtpd/smtp.py", line 122, in _call_handler_hook
    status = await hook(self, self.session, self.envelope, *args)
  File "/usr/src/app/src/aiosmtpd/aiosmtpd/handlers.py", line 156, in handle_DATA
    self.handle_message(envelope)
  File "/usr/src/app/handler.py", line 28, in handle_message
    self.send_to_slack(self.extract_text(message), **options)
  File "/usr/src/app/handler.py", line 75, in send_to_slack
    icon_url=options['icon_url']
  File "/usr/local/lib/python3.6/site-packages/slack/chat.py", line 49, in post_message
    return slack.http_client.post('chat.postMessage', data)
  File "/usr/local/lib/python3.6/site-packages/slack/http_client.py", line 42, in post
    return _parse_response(response)
  File "/usr/local/lib/python3.6/site-packages/slack/http_client.py", line 49, in _parse_response
    _raise_error_if_not_ok(response)
  File "/usr/local/lib/python3.6/site-packages/slack/http_client.py", line 72, in _raise_error_if_not_ok
    raise SlackError(response['error'])
slack.exception.SlackError: missing_scope
```

This is my config.yml:

```
default:
    channel: '#mychannel'
    username: slacker
    icon_url: ''
    slack_token: xoxb
    debug: false
    format: "subject: %(subject)s; body: %(body)s"  ## default slack message format


rules:
    - name: "Catch them all"
      from: ".*"

      options:
          username: slacker
          channel: '#mychannel'
          icon_url: ''
          debug: false
```

**Comment by lastb0isct** [comment]
Confirmed this is an issue with my user not having access to create a normal oAuth account -- `Bot User OAuth Token` isn't going to be enough

**Comment by lastb0isct** [comment]
Closed
